# Generated by Django 5.0.8 on 2024-08-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
